### ISSUE TITLE
Receiving 100+ alerts beetween 23:00-00:00

### ISSUE THREAD

**Issue by caseyrweiss** [netmet1/constellation-node-automation#8]
I have my config.yaml setup for hourly alerts from 00:00 to 00:00.  During the 24th hour I receive an alert every few seconds for a total over 100+ alert.

Here is a snippet from my email inbox with the timestamps:
<img width="141" alt="Screen Shot 2021-10-09 at 4 48 23 PM" src="https://user-images.githubusercontent.com/90288183/136676558-f81f6d81-371e-4848-9dbb-04cf73bb7a23.png">
s.

**Comment by netmet1** [comment]
I'll take a look at this and get it figured out... asap!
Can you please provide the `intervals` section of your `config.yaml` for review.

Please also make sure that your `start_time` and `end_time` are in quotes

```
intervals:
  enabled: true
  time_zone: UTC
  start_time: '00:00'
  end_time: '00:00'
  int_minutes: 15
```
